# This is a basic workflow to help you get started with Actions

name: raw_dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:  
      - "raw/**"
      - ".github/workflows/raw.yaml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LiquibaseDockerCLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV  
    - name: Run ' Liquibase status' in Docker
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="${{ secrets.SF_URL }}/?db=${{ secrets.SF_DATABASE_RAW}}_${{env.GIT_BRANCH != 'main' && env.GIT_BRANCH || 'prd'}}&schema=LIQUIBASE" --changeLogFile=/raw/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --logLevel=debug status
    - name: Run ' Liquibase update' in Docker
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="${{ secrets.SF_URL }}/?db=${{ secrets.SF_DATABASE_RAW}}_${{env.GIT_BRANCH != 'main' && env.GIT_BRANCH || 'prd'}}&schema=LIQUIBASE" --changeLogFile=/raw/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --logLevel=debug update
    
